services:
  db:
    image: mysql:8.0
    container_name: image_tagger_mbit_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pictures
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: .
    image: image_tagger_mbit:latest
    container_name: image_tagger_mbit
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      FLASK_APP: app
      FLASK_ENV: development
    volumes:
      - uploads:/usr/src/app/uploads
volumes:
  db_data:
  uploads: